# 1
version: '3.7'

# 2
volumes:
  db_data:

# 3
x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_NAME: vapor_database
  DATABASE_USERNAME: vapor_username
  DATABASE_PASSWORD: vapor_password

# 4
services:
  # 5
  app:
    # 6
    image: cookbook:latest
    # 7
    build:
      context: .
    # 8
    environment:
      <<: *shared_environment
    # 9
    depends_on:
      - db
    # 10
    ports:
      - '8080:8080'
    # 11
    command: ["serve", "--env", "production", "--hostname", 
              "0.0.0.0", "--port", "8080"]
  # 12
  db:
    # 13
    image: postgres:12-alpine
    # 14
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    # 15
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    ports:
      - '5432:5432'